# Generated by Django 4.1.4 on 2023-04-05 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 4, 5, 21, 11, 47, 418765)
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=200)),
                ("body", models.CharField(max_length=200)),
                ("parent", models.PositiveIntegerField(default=0)),
                ("likecount", models.IntegerField(default=0)),
                ("replycount", models.IntegerField(default=0)),
                ("isreply", models.BooleanField(default=False)),
                ("replyingto", models.CharField(max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommentReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 4, 5, 21, 11, 47, 419161)
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=200)),
                ("body", models.CharField(max_length=200)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comments.comment",
                    ),
                ),
            ],
        ),
    ]
