# Generated by Django 4.1.4 on 2023-04-05 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 5, 21, 12, 44, 71100)
            ),
        ),
        migrations.AlterField(
            model_name="commentreply",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 5, 21, 12, 44, 71488)
            ),
        ),
    ]
