# Generated by Django 4.1.4 on 2023-04-05 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_alter_comment_date_alter_commentreply_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="commentreply",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
