# Generated by Django 4.2 on 2023-05-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_date_alter_commentreply_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='isreply',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='replyingto',
            new_name='to',
        ),
    ]
