# Generated by Django 4.2 on 2023-05-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_remove_comment_reply_remove_comment_replys_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_post',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
