# Generated by Django 4.2 on 2023-05-09 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_rename_parent_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='parent_post',
            new_name='post',
        ),
    ]
