# Generated by Django 4.2 on 2023-05-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_remove_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='children',
        ),
        migrations.AddField(
            model_name='comment',
            name='has_replys',
            field=models.BooleanField(default=False),
        ),
    ]
