# Generated by Django 4.1.4 on 2023-01-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
