# Generated by Django 4.1.4 on 2023-01-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0007_remove_post_image_image_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(to="feed.image"),
        ),
    ]
