# Generated by Django 4.1.4 on 2023-01-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0011_post_favorites_post_likes_commentobj_post_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(blank=True, to="feed.commentobj"),
        ),
    ]
