# Generated by Django 4.1.4 on 2023-01-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0012_alter_post_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
