# Generated by Django 4.2.1 on 2023-06-12 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reccomendations', '0002_alter_userinterest_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInterest',
            new_name='Interest',
        ),
    ]
