# Generated by Django 4.1.4 on 2023-04-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_useraccount_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": {"errors": "This email has already been registered."}
                },
                max_length=225,
                unique=True,
            ),
        ),
    ]
