# Generated by Django 4.1.4 on 2023-04-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_useraccount_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "This email has already been registered."},
                max_length=225,
                unique=True,
            ),
        ),
    ]
