# Generated by Django 4.2 on 2023-04-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraccount_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
