# Generated by Django 4.2 on 2023-04-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraccount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
