# Generated by Django 4.2 on 2023-04-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_useraccount_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='pfp',
            field=models.ImageField(default='c0c216b3743c6cb9fd67ab7df6b2c330.jpg', upload_to=''),
        ),
    ]
