# Generated by Django 4.2 on 2023-04-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useraccount_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
