# Generated by Django 4.2.1 on 2023-06-06 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_useraccount_followers_useraccount_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='useraccount_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='useraccount_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
