# Generated by Django 4.2.1 on 2023-06-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_useraccount_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
