# Generated by Django 4.1.4 on 2023-04-05 21:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hashtags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=42, null=True)),
                ("title", models.CharField(max_length=40)),
                ("desc", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 4, 5, 21, 11, 53, 50808)
                    ),
                ),
                ("likecount", models.IntegerField(default=0)),
                ("postcount", models.IntegerField(default=0)),
                ("commentcount", models.IntegerField(default=0)),
                ("page", models.IntegerField(null=True)),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("hashtags", models.ManyToManyField(blank=True, to="hashtags.hashtag")),
                ("images", models.ManyToManyField(blank=True, to="posts.image")),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
