# Generated by Django 4.2.1 on 2023-05-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='target_user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='user',
            new_name='sender',
        ),
    ]
