# Generated by Django 4.2.1 on 2023-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0004_alter_chatroom_receiver_alter_chatroom_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='receiver',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='sender',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
