# Generated by Django 4.2.1 on 2023-05-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0007_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='message',
        ),
        migrations.AddField(
            model_name='messages',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Messaging.chatroom'),
            preserve_default=False,
        ),
    ]
