# Generated by Django 4.2.1 on 2023-05-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Messaging', '0008_remove_chatroom_message_messages_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='receiver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
