# Generated by Django 4.2.1 on 2023-05-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0009_remove_chatroom_receiver_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='parent',
        ),
        migrations.AddField(
            model_name='messages',
            name='room_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
