# Generated by Django 4.2.1 on 2023-05-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0010_rename_content_messages_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
