# Generated by Django 4.2.1 on 2023-05-28 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Messaging', '0016_chatroom_receiver_chatroom_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='sender',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
