# Generated by Django 4.1.4 on 2023-01-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center_user", "0002_user_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated",
            field=models.DateField(blank=True, null=True),
        ),
    ]
