# Generated by Django 4.1.3 on 2022-11-26 05:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feed", "0002_post_user"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CartModel",
            new_name="Cart",
        ),
    ]
