# Generated by Django 4.1.3 on 2022-11-26 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_post_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0003_cart_cart_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="post",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="qty",
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField(default=1)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="feed.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="cartitems",
            field=models.ManyToManyField(to="cart.cartitem"),
        ),
    ]
