# Generated by Django 4.1.3 on 2022-11-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_remove_cart_post_remove_cart_qty_cartitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="total",
            field=models.FloatField(default=0),
        ),
    ]
