# Generated by Django 4.1.4 on 2022-12-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_address_delete_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="is_billing",
            new_name="def_address",
        ),
    ]
