# Generated by Django 4.1.4 on 2022-12-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_rename_street_adress_address_street_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="apartment",
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
