# Generated by Django 4.1.4 on 2022-12-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_alter_address_apartment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="def_address",
            field=models.BooleanField(null=True),
        ),
    ]
