# Generated by Django 4.1.4 on 2022-12-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_alter_address_def_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="def_address",
        ),
    ]
