# Generated by Django 4.1.4 on 2022-12-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_remove_address_def_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="stateforeign",
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
