# Generated by Django 4.1.4 on 2022-12-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0015_order_completed_alter_order_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="completed",
            new_name="paid",
        ),
    ]
