# Generated by Django 4.1.4 on 2022-12-26 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0016_rename_completed_order_paid"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=999)),
                ("street_address", models.CharField(max_length=999)),
                ("apartment", models.CharField(blank=True, max_length=999, null=True)),
                ("country", models.CharField(max_length=999)),
                ("state", models.CharField(max_length=999)),
                ("zip_code", models.IntegerField()),
                ("selected", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
