# Generated by Django 4.1.4 on 2022-12-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0017_billingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
