# Generated by Django 4.1.4 on 2022-12-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0018_cartitem_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
