# Generated by Django 4.1.4 on 2022-12-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0019_cartitem_date_delete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="orderid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
