# Generated by Django 4.1.4 on 2022-12-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0020_cartitem_orderid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="orderid",
        ),
    ]
