# Generated by Django 4.1.4 on 2022-12-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0021_remove_cartitem_orderid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="cartid",
            field=models.IntegerField(null=True),
        ),
    ]
