# Generated by Django 4.1.4 on 2022-12-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0022_cartitem_cartid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cartid",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cartkey",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
