# Generated by Django 4.1.4 on 2022-12-29 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0024_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.cartitem",
            ),
        ),
    ]
