# Generated by Django 4.1.4 on 2022-12-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0025_alter_order_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="item",
        ),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(null=True, to="cart.cartitem"),
        ),
    ]
