# Generated by Django 4.1.4 on 2022-12-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0026_remove_order_item_order_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(to="cart.cartitem"),
        ),
    ]
