# Generated by Django 4.1.4 on 2022-12-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0027_alter_order_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cartkey",
        ),
    ]
