# Generated by Django 4.1.4 on 2022-12-30 03:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_remove_post_in_carts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0028_remove_cartitem_cartkey"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order",
            new_name="Cart",
        ),
        migrations.RenameModel(
            old_name="CartItem",
            new_name="Item",
        ),
    ]
