# Generated by Django 4.1.4 on 2022-12-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0029_rename_order_cart_rename_cartitem_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="total",
        ),
    ]
