# Generated by Django 4.1.4 on 2023-01-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0031_address_samebilling"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="item",
            new_name="manytomanyitm",
        ),
    ]
