# Generated by Django 4.1.4 on 2023-01-06 06:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0032_rename_item_cart_manytomanyitm"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BillingAddress",
            new_name="Billing",
        ),
    ]
