# Generated by Django 4.1.4 on 2023-01-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0033_rename_billingaddress_billing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="manytomanyitm",
            new_name="items",
        ),
    ]
